requires 'YAML';
requires 'Getopt::Long';
requires 'FindBin';
requires 'Path::Class::Dir';
requires 'File::ChangeNotify';
requires 'Color::ANSI::Util';
requires 'Text::Wrap';
requires 'DB_File';
requires 'JSON::XS';
